spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3306/auto-ria?createIfNotExist=true
    username: root
    password: root
  mail:
    host: smtp.gmail.com
    username: milansomyk@gmail.com
    password: vapcnbuemszhqbfe
    properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

jwt:
  signingKey: super_long_secret_key_that_nobody_knows
